### ISSUE TITLE
nhibernate.bytecode.castle could not be loaded

### ISSUE THREAD

**Issue by defyjoy** [sharparchitecture/Sharp-Architecture-Cookbook#1]
i am using windows 7 x64. the sample worked wonderfully under windows xp . but somehow i am getting this error 

Unable to load type 'NHibernate.ByteCode.Castle.ProxyFactoryFactory, NHibernate.ByteCode.Castle' during configuration of proxy factory class.
Possible causes are:
- The NHibernate.Bytecode provider assembly was not deployed.
- The typeName used to initialize the 'proxyfactory.factory_class' property of the session-factory section is not well formed.

Solution:
Confirm that your deployment folder contains one of the following assemblies:
NHibernate.ByteCode.LinFu.dll
NHibernate.ByteCode.Castle.dll

under windows 7 x64. i tried to copy the Nhibernate.Bytecode.Castle under bin and referencing it to the project . but all was in vain. can you please fix this issue under x64 machines ? and also to resolve i tried to run it under x64 build configuration from project properties its then giving error as d same . please have a look at this issue

**Comment by chrisrichards** [comment]
This was something I missed in the upgrade to NH 3.2, you just need to remove setting the proxyfactory property in the NHibernate.config file. Also, The ProductsForSaleQuery class was not public so was not being registered with Castle.

I've just committed these updates so if you update to the latest it should be OK again.

**Comment by defyjoy** [comment]
thanks for the Apt reply.... cause i m very new to sharp architecture... i cdnt fix these error myself.. thanks for ur apt reply and support.... i wd download and check it out ASAP.
