### ISSUE TITLE
Recipe #002 - using iquery&lt;t&gt; not up to date

### ISSUE THREAD

**Issue by DavidSSL** [sharparchitecture/Sharp-Architecture-Cookbook#3]
On the front page of the Wiki for the cookbook, this Recipe doesn't appear in the list of Recipes. Moreover, the code as of today 29 Nov 2011, doesn't match what's in that recipe. The code is in fact using the Recipe 1. Does it mean that it is recommended that this recipe is not to be used? If so why?

Sorry, I know this is not the support page but other people who will download the code and try to follow the Wiki will likely come across the same concerns that I have.

**Comment by chrisrichards** [comment]
IQuery<T> has been removed from Sharp-Architecture as it was causing too much confusion, see Geoff's comment on the commit https://github.com/sharparchitecture/Sharp-Architecture/commit/80fe2da6d61852f142cf52dd762d3bb91aacad09#commitcomment-505286

**Comment by DavidSSL** [comment]
Hi Chris, 

Thanks for that. Maybe removing or disabling that section from the wiki would be useful for others who come to exploring S#arp architecture.
