### ISSUE TITLE
Nhibernate configuration life cycle - Why file instead memory?

### ISSUE THREAD

**Issue by lmorduhay** [sharparchitecture/Sharp-Architecture-Cookbook#4]
Hi gays, it comes to me the idea of why doesnt NH crew provide a singleton on the configuraction object/s that allow us just load configuration for our Web apps on application start (lets say in Application_start event on global.asax).

Even more, if they dont, you did, but why to serilize objects in a file (i understund you do such a thing because the user of NHibernateConfigurationFileCache) and not not keep the configuration in memory (may be is to expensive...)? 
You are smart people so im sure there is a good explanation.

Cheers.

**Comment by seif** [comment]
The session factory is expensive to initialize and should be done once. After the factory is initialized it is kept in memory, the caching to file is done so that when the app pool restarts it wouldnt have to re-init the factory, and just deserialize the cached version.

**Comment by lmorduhay** [comment]
Beautiful, thanks for the explanation.
